=== yannickcr/k1der/modules/serveur/jeux/jeu.dtd
<!ELEMENT jeu ((gametype)+,maps) >
<!ATTLIST jeu
	name		CDATA							#REQUIRED
	shortname	CDATA							#REQUIRED
>
<!ELEMENT gametype EMPTY>
<!ATTLIST gametype
	nom			CDATA							#REQUIRED
	type		(Team|Duel|Deathmatch)			"Duel"
	nbplayer	CDATA							#REQUIRED
	team1		CDATA							#IMPLIED
	team2		CDATA							#IMPLIED
	round		CDATA							#IMPLIED
	minmaps		CDATA							#REQUIRED
	maxmaps		CDATA							#REQUIRED
>
<!ELEMENT maps ((map)+) >
<!ELEMENT map EMPTY>
<!ATTLIST map
	nom			CDATA							#REQUIRED
	image		CDATA							"../nomap.jpg"
>

=== yannickcr/k1der/modules/serveur/jeux/css/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jeu SYSTEM "../jeu.dtd">
<jeu name="Counter-Strike: Source" shortname="css">
	<gametype nom="5 vs 5" type="Team" nbplayer="5" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<gametype nom="2 vs 2" type="Team" nbplayer="2" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<maps>
		<map nom="cs_assault" image="maps/cs_assault.jpg" />
		<map nom="cs_compound" image="maps/cs_compound.jpg" />
		<map nom="cs_havana" image="maps/cs_havana.jpg" />
		<map nom="cs_italy" image="maps/cs_italy.jpg" />
		<map nom="cs_office" image="maps/cs_office.jpg" />
		<map nom="de_aztec" image="maps/de_aztec.jpg" />
		<map nom="de_cbble" image="maps/de_cbble.jpg" />
		<map nom="de_chateau" image="maps/de_chateau" />
		<map nom="de_dust" image="maps/de_dust.jpg" />
		<map nom="de_dust2" image="maps/de_dust2.jpg" />
		<map nom="de_inferno" image="maps/de_inferno.jpg" />
		<map nom="de_piranesi" image="maps/de_piranesi.jpg" />
		<map nom="de_prodigy" image="maps/de_prodigy.jpg" />
		<map nom="de_port" image="maps/de_port.jpg" />
		<map nom="de_train" image="maps/de_train.jpg" />
		<map nom="de_tides" image="maps/de_tides.jpg" />
	</maps>
</jeu>

=== yannickcr/k1der/modules/matches/jeux/hl2dm/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jeu SYSTEM "../jeu.dtd">
<jeu name="Half-Life Deathmatch" shortname="hl2dm">
	<gametype nom="Duel" type="Duel" nbplayer="1" minmaps="1" maxmaps="3" />
	<gametype nom="5 vs 5" type="Team" nbplayer="5" minmaps="1" maxmaps="3" />
	<gametype nom="Deathmatch" type="Deathmatch" nbplayer="8" minmaps="1" maxmaps="1" />
	<maps>
		<map nom="dm_lockdown" image="maps/dm_lockdown.jpg" />
		<map nom="dm_overwatch" image="maps/dm_overwatch.jpg" />
		<map nom="dm_powerhouse" image="maps/dm_powerhouse.jpg" />
		<map nom="dm_resistance" image="maps/dm_resistance.jpg" />
		<map nom="dm_runoff" image="maps/dm_runoff.jpg" />
		<map nom="dm_steamlab" image="maps/dm_steamlab.jpg" />
		<map nom="dm_underpass" image="maps/dm_underpass.jpg" />
	</maps>
</jeu>

=== yannickcr/k1der/modules/matches/jeux/cs/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jeu SYSTEM "../jeu.dtd">
<jeu name="Counter-Strike" shortname="cs">
	<gametype nom="5 vs 5" type="Team" nbplayer="5" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<gametype nom="2 vs 2" type="Team" nbplayer="2" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<gametype nom="Duel" type="Duel" nbplayer="1" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<gametype nom="3 vs 3" type="Team" nbplayer="3" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<gametype nom="4 vs 4" type="Team" nbplayer="4" team1="T" team2="CT" round="2" minmaps="1" maxmaps="3" />
	<maps>
		<map nom="cs_747" image="maps/cs_747.jpg" />
		<map nom="cs_assault" image="maps/cs_assault.jpg" />
		<map nom="cs_havana" image="maps/cs_havana.jpg" />
		<map nom="cs_italy" image="maps/cs_italy.jpg" />
		<map nom="cs_militia" image="maps/cs_militia.jpg" />
		<map nom="cs_office" image="maps/cs_office.jpg" />
		<map nom="cs_siege" image="maps/cs_siege.jpg" />
		<map nom="de_aztec" image="maps/de_aztec.jpg" />
		<map nom="de_cbble" image="maps/de_cbble.jpg" />
		<map nom="de_dust" image="maps/de_dust.jpg" />
		<map nom="de_dust2" image="maps/de_dust2.jpg" />
		<map nom="de_inferno" image="maps/de_inferno.jpg" />
		<map nom="de_nuke" image="maps/de_nuke.jpg" />
		<map nom="de_piranesi" image="maps/de_piranesi.jpg" />
		<map nom="de_prodigy" image="maps/de_prodigy.jpg" />
		<map nom="de_train" image="maps/de_train.jpg" />
		<map nom="de_vertigo" image="maps/de_vertigo.jpg" />
	</maps>
</jeu>

=== yannickcr/k1der/modules/matches/jeux/cmr4/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE jeu SYSTEM "../jeu.dtd">
<jeu name="Colin McRae Rally 04" shortname="cmr4">
	<gametype nom="Deathmatch" type="Deathmatch" nbplayer="6" minmaps="1" maxmaps="1" />
	<gametype nom="Duel" type="Duel" nbplayer="1" minmaps="1" maxmaps="3" />
	<maps>
		<map nom="Australie" image="speciales/australie.jpg" />
		<map nom="Espagne" image="speciales/espagne.jpg" />
		<map nom="Etats-Unis" image="speciales/etatsunis.jpg" />
		<map nom="Finlande" image="speciales/finlande.jpg" />
		<map nom="Grce" image="speciales/grece.jpg" />
		<map nom="Japon" image="speciales/japon.jpg" />
		<map nom="Royaume Uni" image="speciales/royaumeuni.jpg" />
		<map nom="Sude" image="speciales/suede.jpg" />
	</maps>
</jeu>
