=== yannickcr/k1der/include/config.dtd
<!ELEMENT configuration (pages,(actions)*,(admin)*) >
<!ATTLIST page
	titre			CDATA			#IMPLIED
>
<!ELEMENT pages (page)+>
<!ELEMENT page EMPTY>
<!ATTLIST page
	page			CDATA			#REQUIRED
	condition		CDATA			""
>
<!ELEMENT actions (action)*>
<!ELEMENT action EMPTY>
<!ATTLIST action
	action			CDATA			#REQUIRED
	condition		CDATA			""
>
<!ELEMENT admin (menu)*>
<!ATTLIST admin
	titre			CDATA			#REQUIRED
>
<!ELEMENT menu EMPTY>
<!ATTLIST menu
	titre			CDATA			#REQUIRED
	lien			CDATA			#REQUIRED
>

=== yannickcr/k1der/modules/quote/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration>
	<pages>
		<page page="random" condition="post[action](random)" />
	</pages>
	<actions>
		<action action="addPhrase" condition="post[auteur],post[phrase]" />
		<action action="editPhrase" condition="get[id],post[auteur],post[phrase]" />
		<action action="delPhrase" condition="get[id]" />
	</actions>
	<admin titre="Phrases Ã  la cons">
		<menu titre="Ajouter" lien="admin/quote/ajouter.html" />
		<menu titre="Liste des phrases" lien="admin/quote/liste.html" />
	</admin>
</configuration>

=== yannickcr/k1der/modules/clans/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration>
	<pages>
		<page page="compolineup" condition="get[module],get[action](composition-line-up)" />
		<page page="livesearchclan" condition="get[livesearchclan],get[q]" />
		<page page="fiche" condition="get[clan]" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="create" condition="post[nom],post[tag],post[tagempl],post[site],post[irc],post[ircserver],infos[id]" />
		<action action="edit" condition="post[nom],post[tag],post[tagempl],post[leader],post[site],post[irc],post[ircserver],infos[id]" />
		<action action="changeBan" condition="post[url],infos[id]" />
		<action action="addLineUp" condition="post[nom],infos[id]" />
		<action action="majLineUp" condition="post[majlineup],infos[id]" />
		<action action="newJoin" condition="post[clan],infos[id]" />
		<action action="annulerJoin" condition="post[annuler],infos[id]" />
		<action action="quit" condition="post[quit],infos[id]" />
		<action action="close" condition="post[close],infos[id]" />

		<action action="supprimerClans" condition="get[action](supprimer),get[id],infos[id]" />
		<action action="configClans" condition="post[clan]" />

	</actions>
	<admin titre="Clans">
		<menu titre="Liste des clans" lien="admin/clans/liste.html" acces="clans_lister" />
		<menu titre="Rechercher un clan" lien="admin/clans/rechercher.html" acces="clans_search" />
		<menu titre="Configuration" lien="admin/clans/configuration.html" acces="clans_config" />
	</admin>
</configuration>

=== yannickcr/k1der/modules/admin/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration titre="Administration">
	<pages>
		<page page="whois" condition="get[ip]" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="configSite" condition="post[defpage],infos[id]" />
		<action action="changeTheme" condition="post[changetheme],infos[id]" />
		<action action="changeSmileys" condition="post[smiley_0],post[smiley_0_txt],infos[id]" />
		<action action="placeModules" condition="post[ordre],infos[id]" />
	</actions>
	<admin titre="Administration du site">
		<menu titre="Configuration" lien="admin/configuration.html" acces="admin_config" />
		<menu titre="Apparence" lien="admin/apparence.html" acces="admin_apparence" />
		<menu titre="Placement des modules" lien="admin/modules.html" />
		<menu titre="AccÃ¨s" lien="admin/acces.html" acces="admin_acces" />
		<menu titre="Smileys" lien="admin/smileys.html" acces="admin_smileys" />
	</admin>
</configuration>
