=== yannickcr/k1der/include/config.dtd
<!ELEMENT configuration (pages,(actions)*,(admin)*) >
<!ATTLIST page
	titre			CDATA			#IMPLIED
>
<!ELEMENT pages (page)+>
<!ELEMENT page EMPTY>
<!ATTLIST page
	page			CDATA			#REQUIRED
	condition		CDATA			""
>
<!ELEMENT actions (action)*>
<!ELEMENT action EMPTY>
<!ATTLIST action
	action			CDATA			#REQUIRED
	condition		CDATA			""
>
<!ELEMENT admin (menu)*>
<!ATTLIST admin
	titre			CDATA			#REQUIRED
>
<!ELEMENT menu EMPTY>
<!ATTLIST menu
	titre			CDATA			#REQUIRED
	lien			CDATA			#REQUIRED
>

=== yannickcr/k1der/modules/membres/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "http://www.k1der.net/include/config.dtd">
<configuration>
	<pages>
		<page page="inscription" condition="get[module],get[inscription](1)" />
		<page page="inscriptionfinish" condition="get[module],get[inscription](2)" />
		<page page="reglement" condition="get[module],get[action](reglement)" />
		<page page="recupmdp" condition="get[module],get[action](recupmdp)" />
		<page page="recupmdpfinish" condition="get[module],get[action](recupmdpfinish)" />
		<page page="activer" condition="get[module],get[activer]" />
		<page page="newmdp" condition="get[module],get[newmdp]" />
		<page page="newmdpfinish" condition="get[module],get[action](newmdpfinish)" />
		<page page="logout" condition="get[logout]" />
		<page page="mon-profil" condition="get[profil]" />
		<page page="livesearch" condition="get[livesearch],get[q]" />
		<page page="profil" condition="get[membre]" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="changeAvatar" condition="post[avatar],post[url],infos[id]" />
		<action action="editInfos" condition="post[nom],post[prenom],post[www],post[jour],post[mois],post[annee],post[natio],post[mail],post[msn],post[icq],post[aim],post[yahoo],post[hard_1],post[hard_2],post[hard_3],post[hard_4],post[hard_5],infos[id]" />
		<action action="editSignature" condition="post[message],infos[id]" />
		<action action="inscription" condition="post[pseudo],post[email],post[reglement]" />
		<action action="recupMDP" condition="post[email]" />
		<action action="newMDP" condition="post[pass],post[confpass]" />
		<action action="changeMDP" condition="post[pass],post[confpass]" />
		<action action="makeMessage" condition="post[to],post[sujet],post[message]" />
		
		<action action="markMessages" condition="post[message],post[mark]" />
		<action action="delMessages" condition="post[message],post[del]" />

		<action action="configMembres" condition="post[inscr],post[mailtitle],post[mailtxt]" />
		<action action="niveauxMembres" condition="post[points1],post[design1],post[image1]" />
		<action action="editMembres" condition="post[nom],post[prenom],post[www],post[jour],post[mois],post[annee],post[natio],post[mail],post[msn],post[icq],post[aim],post[yahoo],post[hard_1],post[hard_2],post[hard_3],post[hard_4],post[hard_5]" />
		<action action="supprimerMembres" condition="get[action](supprimer),get[id]" />
		<action action="changeMembresAvatar" condition="post[avatar],post[url],infos[id]" />
		<action action="modifierMessage" condition="post[messagetxt],post[messagetitle],infos[id]" />
		<action action="updateAcces" condition="post[submit]" />
		<action action="creerBlog" condition="post[blog],post[pass],post[pass2]" />
	</actions>
	<admin titre="Membres">
		<menu titre="Liste des membres" lien="admin/membres/liste.html"/>
		<menu titre="Rechercher un membre" lien="admin/membres/rechercher.html"/>
		<menu titre="Niveaux des membres" lien="admin/membres/niveaux.html"/>
		<menu titre="Messages automatiques" lien="admin/membres/liste-messages.html"/>
		<menu titre="Configuration" lien="admin/membres/configuration.html"/>
	</admin>
</configuration>

=== yannickcr/k1der/modules/forum/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration titre="Forum">
	<pages>
		<page page="search" condition="get[module],get[action](search),get[search]" />
		
		<page page="viewcat" condition="get[module],get[cat]" />
		<page page="writetopic" condition="get[module],get[forum],get[new]" />
		<page page="listtopics" condition="get[module],get[forum]" />
		<page page="writepost" condition="get[module],get[topic],get[reply]" />
		<page page="delpost" condition="get[module],get[topic],get[del]" />

		<page page="deltopic" condition="get[module],get[topic],post[option](del)" />
		<page page="movetopic" condition="get[module],get[topic],post[option](move)" />
		<page page="closetopic" condition="get[module],get[topic],post[option](close)" />
		<page page="opentopic" condition="get[module],get[topic],post[option](open)" />
		<page page="pintopic" condition="get[module],get[topic],post[option](pin)" />
		<page page="unpintopic" condition="get[module],get[topic],post[option](unpin)" />
		
		<page page="viewtopic" condition="get[module],get[topic]" />
		<page page="liveedit" condition="get[action](liveedit)" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="delPost" condition="get[del],post[valider]" />
		<action action="delTopic" condition="get[topic],post[valider]" />
		<action action="moveTopic" condition="get[topic],post[forum]" />
		<action action="closeTopic" condition="get[topic],post[valider]" />
		<action action="openTopic" condition="get[topic],post[valider]" />
		<action action="pinTopic" condition="get[topic],post[valider]" />
		<action action="unpinTopic" condition="get[topic],post[valider]" />
		
		<action action="vote" condition="post[vote]" />
		<action action="showVotes" condition="post[showvotes]" />
		<action action="showOptions" condition="post[showoptions]" />
		<action action="reply" condition="post[message],post[valider],!get[edit]" />
		<action action="preview" condition="post[message],post[previsualiser]" />
		<action action="quote" condition="get[quote]" />
		<action action="editReply" condition="get[edit],post[valider]" />
		<action action="edit" condition="get[edit],!post[previsualiser]" />
		<action action="newTopic" condition="post[message],post[valider],!get[edit],!get[poll]" />
		<action action="newPoll" condition="post[message],post[valider],!get[edit],get[poll]" />
		<action action="editPoll" condition="get[edit],post[message],post[valider]" />
		<action action="editTopic" condition="get[edit],post[message],post[valider]" />
		
		<action action="addForum" condition="post[cat],post[nom],post[descr]" />
		<action action="editForum" condition="post[cat],post[nom],post[descr]" />
		<action action="addCat" condition="post[nom]" />
		<action action="configForum" condition="post[nbmess]" />
		<action action="supprCat" condition="post[moveto]" />
		<action action="supprForum" condition="post[moveto]" />
		<action action="editDroits" condition="post[submit]" />
		<action action="emptyForum" condition="post[empty]" />
		<action action="renCat" condition="post[nom]" />
		
	</actions>
	<admin titre="Forum">
		<menu titre="Ajouter une catégorie" lien="admin/forum/addcat.html" acces="forum_addcat" />
		<menu titre="Ajouter un forum" lien="admin/forum/addforum.html" acces="forum_addforum" />
		<menu titre="Gérer le forum" lien="admin/forum/gererforum.html" acces="forum_gererforum" />
		<menu titre="Configuration" lien="admin/forum/configuration.html" acces="forum_config" />
	</admin>
</configuration>

=== yannickcr/k1der/modules/download/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration>
	<pages>
		<page page="fiche" condition="get[file]" />
		<page page="cat" condition="get[cat]" />
		<page page="count" condition="post[id]" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="addComm" condition="get[file],post[message],post[note]" />
		<action action="editComm" condition="get[file],get[edit],post[message],post[note]" />
		<action action="delComm" condition="get[file],get[del]" />
		
		<action action="addFile" condition="post[nom],post[cat],post[descr],post[miroir],infos[id]" />
		<action action="addCat" condition="post[cat],post[nom],post[descr],infos[id]" />
		<action action="editCat" condition="post[cat],post[nom],post[descr],get[id],infos[id]" />
		<action action="editFile" condition="post[nom],post[cat],post[descr],post[miroir],get[id],infos[id]" />
		<action action="delCat" condition="get[id]" />
		<action action="delFile" condition="get[id]" />
		<action action="moveCat" condition="get[id],get[action2]" />
		<action action="moveFile" condition="get[id],get[action2]" />
	</actions>
	<admin titre="Téléchargements">
		<menu titre="Ajouter une catégorie" lien="admin/download/addcat.html"/>
		<menu titre="Ajouter un fichier" lien="admin/download/addfile.html"/>
		<menu titre="Gérer des téléchargements" lien="admin/download/gerercat.html"/>
	</admin>
</configuration>

=== yannickcr/k1der/modules/wap/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration titre="iMode">
	<pages>
		<page page="forum" condition="get[action](forum)" />
		<page page="shoutbox" condition="get[action](shoutbox)" />
		<page page="readnews" condition="get[action](news),get[param]" />
		<page page="news" condition="get[action](news)" />
		<page page="index" condition="" />
	</pages>
	<actions>
	</actions>
	<admin titre="iMode">
	</admin>
</configuration>

=== yannickcr/k1der/modules/matches/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration>
	<pages>
		<page page="livesearchplayer" condition="get[livesearchplayer],get[id],get[q]" />
		<page page="livesearchadv" condition="get[livesearchadv],get[id],get[q]" />
		<page page="livesearchlan" condition="get[livesearchlan],get[q]" />
		
		<page page="reloadxmlpart" condition="get[loadxml],get[reloadxmlpart],get[data]" />
		<page page="loadxml" condition="get[loadxml]" />
		<page page="matche" condition="get[action](matche),get[id]" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="modifierMatch" condition="get[id],post[jeu],post[type],post[lieu],post[mode],post[joueur1],post[adv1],infos[id]" />
		<action action="ajouterMatch" condition="post[jeu],post[type],post[lieu],post[mode],post[joueur1],post[adv1],infos[id]" />
		<action action="supprimerMatch" condition="get[action](supprimer),get[id],infos[id]" />

		<action action="addComm" condition="get[id],post[message],post[note]" />
		<action action="editComm" condition="get[id],get[edit],post[message],post[note]" />
		<action action="delComm" condition="get[id],get[del]" />
	</actions>
	<admin titre="Matches">
		<menu titre="Ajouter" lien="admin/matches/ajouter.html"/>
		<menu titre="Liste des matches" lien="admin/matches/liste.html"/>
	</admin>
</configuration>

=== yannickcr/k1der/modules/news/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration titre="Actualités">
	<pages>
		<page page="news" condition="get[module],get[id]" />
		<page page="jour" condition="get[module],get[date]" />
		<page page="index" condition="" />
	</pages>
	<admin titre="News">
		<menu titre="Configuration" lien="ajout_cat"/>
		<menu titre="Gérer les catégories" lien="ajout_cat"/>
	</admin>
</configuration>

=== yannickcr/k1der/modules/shoutbox/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration titre="Rapid'Chat">
	<pages>
		<page page="aide" condition="get[action](aide)" />
		<page page="liveedit" condition="get[action](liveedit)" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="postMessage" condition="post[shoutbox_message],infos[id]" />
		<action action="editMessage" condition="get[id],post[message]" />
		<action action="delMessage" condition="get[id]" />
		<action action="config" condition="post[maxcaract],post[maxlength]" />
	</actions>
	<admin titre="Shoutbox">
		<menu titre="Configuration" lien="admin/shoutbox/configuration.html" />
		<menu titre="Liste des messages" lien="admin/shoutbox/liste.html" />
	</admin>
</configuration>

=== yannickcr/k1der/modules/galeries/config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "../../include/config.dtd">
<configuration titre="Galeries">
	<pages>
		<page page="photo" condition="get[id],get[photo]" />
		<page page="galeries" condition="get[action](galeries)" />
		<page page="galerie" condition="get[id]" />
		<page page="index" condition="" />
	</pages>
	<actions>
		<action action="addGallery" condition="post[nom],post[descr],post[jour],post[mois],post[annee],post[jour2],post[mois2],post[annee2]" />

		<action action="addComm" condition="get[id],get[photo],post[message],post[note]" />
		<action action="editComm" condition="get[id],get[photo],get[edit],post[message],post[note]" />
		<action action="delComm" condition="get[id],get[photo],get[del]" />
	</actions>
	<admin titre="Galeries">
		<menu titre="Ajouter une galerie" lien="admin/galeries/addgallery.html" />
	</admin>
</configuration>
